name: Download Daily Image

on:
  schedule:
    - cron: '0 15 * * *'  # UTC时间15点=北京时间23点（+8 为北京时间）
  push:
    branches:
      - main

jobs:
  download_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests Pillow

    - name: Download and process image
      run: python ./download_image.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'daily update'
        git push
